Display error message for missing issuer name or tx amount
cardstack/cardstack pull request #1663
Opened 2021-06-02 23:04 UTC by burieberry

CS-897

- Update boxel version
- Display required field error message on input or on blur for the Issuer Name field in Layout Customization card
- Initial pass error message display for transaction-amount input field. Can remove those if necessary.

<img width="662" alt="req" src="https://user-images.githubusercontent.com/16160806/120562344-35eade80-c3d4-11eb-9f9c-f74e813f443e.png">

<img width="626" alt="bal" src="https://user-images.githubusercontent.com/16160806/120562385-49964500-c3d4-11eb-8213-476b0b885e2d.png">

@lukemelia & @Aierie Still a couple of things remaining to do but it's ready for a review. 

To do:
- Move `ember-unique-id-helper-polyfill` dependency in boxel from devDependencies to dependencies, and remove it from here
- Tests

2021-06-03 09:01 UTC, Aierie requested changes

2021-06-03 09:01 UTC, Aierie commented on packages/web-client/app/components/card-pay/deposit-workflow/transaction-amount/index.hbs
> +          <Boxel::Input
https://app.uniswap.org/#/swap

2021-06-03 09:05 UTC, Aierie commented on packages/web-client/app/components/card-pay/deposit-workflow/transaction-amount/index.hbs
> +          <Boxel::Input
To achieve this, I think we really should change Boxel::Input to use a native html input so we can get both input filtering and the validation errors showing.

2021-06-03 11:13 UTC, Aierie commented on packages/web-client/app/components/card-pay/deposit-workflow/transaction-amount/index.hbs
> +          <Boxel::Input
https://github.com/cardstack/boxel/pull/375

2021-06-03 17:42 UTC, burieberry commented on packages/web-client/app/components/card-pay/deposit-workflow/transaction-amount/index.hbs
> +          <Boxel::Input
I'll update this. It looks like Uniswap disables the CTA past 18 decimal places without explanation. For insufficient balance, they disable the CTA but have the insufficient balance notice shown on the button. 

We get an uncaught error past 18 decimal places and the button is not visually disabled, even though the unlocking process doesn't work. And there's no way to change the input once the button is pressed. I'll see if I can fix that quickly.

2021-06-04 16:59 UTC, Aierie approved these changes

2021-06-04 21:02 UTC, merged