Withdrawal persistence
cardstack/cardstack pull request #2141
Opened 2021-09-24 10:31 UTC by jurgenwerk

2021-09-24 11:30 UTC, jurgenwerk commented on packages/web-client/app/utils/web3-strategies/layer2-chain.ts
> +    let transactionHash = await new Promise<TransactionHash>((res, reject) => {
Previously, the result of this didn't actually throw an error, meaning the error handling in the token bridge card in the withdrawal workflow didn't work.

2021-09-24 11:34 UTC, jurgenwerk commented on packages/web-client/app/components/card-pay/withdrawal-workflow/transaction-amount/index.hbs
> +            @disabled={{or @frozen (eq this.amountCtaState 'memorialized')}}
Disables the amount when the amount has been used for withdrawal operations later on: 

![image](https://user-images.githubusercontent.com/273660/134667622-807827ba-cd6b-42d6-b6de-acd1e246c772.png)

2021-09-24 11:44 UTC, jurgenwerk commented
@lukemelia would appreciate it if you can check this even though it's still a draft. I think the only thing missing here are tests, which I'm currently working on. I have some issues understanding how to use the test layer to resolve the async tasks in tests, for example `awaitBridgingTask` and `resumeClaimBridgedTokensTask`. Maybe it would go faster if you have some time for pairing today?

2021-09-25 19:14 UTC, lukemelia commented
FYI I rebased this on main now that the workflowSession type safety PR is merged.

2021-09-25 20:21 UTC, lukemelia requested changes
The implementation looks good, Matic, and it works great in my testing. Just needs more test coverage.

2021-09-27 07:18 UTC, jurgenwerk commented
@lukemelia great, thanks for rebasing! I'll add more test coverage and wrap this up today.

2021-09-27 12:04 UTC, jurgenwerk commented
@lukemelia I increased the test coverage with a couple of more acceptance tests. Regarding the change in https://github.com/cardstack/cardstack/commit/6fee41aa9d388ca314cd53d00abe55c1081d9290, I couldn't find any regressions 🤷‍♂️ I think this is now safe to merge, let me know if you have any comments.

2021-09-27 19:19 UTC, merged