Postcss maybe
cardstack/cardstack pull request #2404
Opened 2021-11-22 10:38 UTC by Aierie

Adds postcss to prepend `.ember-application` to css selectors in `web-client`'s components.

2021-11-22 15:49 UTC, Aierie commented on packages/web-client/ember-cli-build.js
> +          }
The `#web-client-root` selector is on the html element, so we don't want to do anything with selectors that are targeting html or root.

2021-11-22 15:50 UTC, Aierie commented on packages/web-client/ember-cli-build.js
> +            },
Necessary because some of web client's css is in `web-client/app/css`

2021-11-22 17:58 UTC, backspace requested changes
I tried this out and didn’t notice any difference in build times, which is excellent! I suggested an update to address a deprecation warning but otherwise looks good to me 🎉

2021-11-22 17:58 UTC, backspace commented on packages/web-client/ember-cli-build.js
> +
I noticed this when running locally:

```
postcss-prepend-selector: postcss.plugin was deprecated. Migration guide:
https://evilmartians.com/chronicles/postcss-8-plugin-migration
```

So I adapted the relevant migration to the Ember CLI context:

```suggestion
const compileCSS = require('broccoli-postcss');
const webpack = require('webpack');

const prependSelector = (opts = {}) => {
  return {
    postcssPlugin: 'postcss-prepend-selector',
    Once(css) {
      css.walkRules(function (rule) {
        rule.selectors = rule.selectors.map(function (selector) {
          if (/(^|\b)(html|:root)\b/.test(selector)) {
            return selector;
          }
          // eslint-disable-next-line no-useless-escape
          if (/^([0-9]*[.])?[0-9]+\%$|^from$|^to$/.test(selector)) {
            // This is part of a keyframe
            return selector;
          }

          if (selector.startsWith(opts.selector.trim())) {
            return selector;
          }

          return opts.selector + selector;
        });
      });
    },
  };
};

```

It seems to have worked!

![image](https://user-images.githubusercontent.com/43280/142911451-20d65367-8805-44c0-a418-cacde75d1834.png)

2021-11-22 18:13 UTC, backspace commented on packages/web-client/ember-cli-build.js
> +
the [migration guide](https://evilmartians.com/chronicles/postcss-8-plugin-migration) has more after that actually, including changing `Once` to `AtRule`, might be worth looking more deeply into. I’m surprised `Once` didn’t need to be imported…???

2021-11-23 15:24 UTC, backspace approved these changes
total success! 🎉

2021-11-23 15:53 UTC, jurgenwerk approved these changes
Looks good!

2021-11-23 16:03 UTC, merged