add fast api and proof indexeer
cardstack/cardstack pull request #2914
Opened 2022-04-27 08:25 UTC by tintinthong

2022-04-27 11:21 UTC, tintinthong commented
Should be mindful that im using amount as string response now rather than integer. This prevents the big number errors from javascript.

2022-05-10 22:14 UTC, IanCal requested changes

2022-05-10 22:14 UTC, IanCal commented on packages/cardpay-sdk/sdk/reward-pool/base.ts
> +    // Subgraph has a max pagination of 100. TODO paginate proofs
Looks like this will be a requirement to get this merged?

2022-05-11 06:23 UTC, tintinthong commented on packages/cardpay-reward-api/cardpay_reward_api/indexer.py
> +                orderDirection: desc
oh I know what u mean.

2022-05-11 07:26 UTC, tintinthong commented on packages/cardpay-reward-api/cardpay_reward_api/indexer.py
> +    def get_merkle_roots(self, reward_program_id: str, block_number: int):
Doubt so. But maybe you can clarify if this is not what you mean. 

It doesn't matter that we get the latest root. We just need to get as many roots as possible; Even if the latest is cut out from pagination. The index point will move up. 

Then in the following task. The newer roots will be indexed

2022-05-12 11:01 UTC, tintinthong commented on packages/cardpay-sdk/README.md
>    tokenAddress: string;
@danibonilha this will not affect the cardwallet will it?

2022-05-12 13:51 UTC, IanCal commented on packages/cardpay-reward-api/cardpay_reward_api/indexer.py
> +    def get_merkle_roots(self, reward_program_id: str, block_number: int):
Ah I see, so the looping here essentially happens with the repeated calls for indexing. That makes sense

2022-05-13 07:41 UTC, tintinthong commented on packages/cardpay-sdk/README.md
>    tokenAddress: string;
thanks I dont think so too

2022-05-13 11:11 UTC, tintinthong commented
@IanCal lemme know if this is good to merge

2022-05-13 11:24 UTC, IanCal commented on packages/cardpay-reward-api/README.md
> +    docker run -v ~/.aws:/root/.aws --env AWS_PROFILE=cardstack-prod --net <some created network> -p 8000:8000 reward-api:latest
https://linear.app/cardstack/issue/CS-3886/add-docker-compose-file-for-api-development

2022-05-13 11:30 UTC, IanCal approved these changes
LGTM code-wise.

@danibonilha Anything we need to be aware of in terms of timing merging and releasing this? It'll be good to test this actually in the app, we can make test payments out to help there.

2022-05-13 13:53 UTC, merged