WIP Boxel::InputGroup
cardstack/cardstack pull request #3290
Opened 2022-10-04 00:00 UTC by lukemelia

2022-10-05 14:38 UTC, danibonilha reviewed
It's looking good to me, but i'll leave to more experienced web devs to approve

2022-10-05 14:58 UTC, lukemelia commented on packages/boxel/addon/components/boxel/input-group/index.css
> +  */
Yes, I will clean that up. Thanks.

2022-10-05 16:07 UTC, backspace commented
I haven’t looked at the code yet but do you think the focus outline can be tweaked? The tiny gaps are irksome to me 😆

<img width="206" alt="Boxel Components 2022-10-05 11-07-23" src="https://user-images.githubusercontent.com/43280/194108685-a682c701-8ca9-45c4-be8c-b8a28a22dbff.png">

Bootstrap:

<img width="148" alt="Input group · Bootstrap v5 2 2022-10-05 11-06-44" src="https://user-images.githubusercontent.com/43280/194108635-2a140db9-f791-4ec9-ad45-ff6404e6adfe.png">

2022-10-05 16:51 UTC, lukemelia commented
@backspace 
> I haven’t looked at the code yet but do you think the focus outline can be tweaked? The tiny gaps are irksome to me 😆
> hmm the preview deployment doesn’t have the copy example? I see it in the template but not rendered:

I've addressed both of those issues. Thanks for catching them.

2022-10-05 17:51 UTC, backspace requested changes
The implementation and interaction looks good to me, Glint feels so powerful 🤩

There are some CSS fixes I think should happen.

The outline for the error state matches but the animation when the state changes should match too; this is at 25% speed to highlight the lag:
![outline-lag](https://user-images.githubusercontent.com/43280/194126354-eefbc9f7-1065-47b7-9f77-0923776dbe44.gif)

Though Bootstrap doesn’t apply the error outline to the accessory at all! 🤔

<img width="262" alt="Validation · Bootstrap v5 2 2022-10-05 12-49-33" src="https://user-images.githubusercontent.com/43280/194127691-39ecf8f9-3f32-444f-ad84-329245e3a49c.png">


It looks broken in Safari, though with focus I think it looks the best of the three browsers I checked:
![safari-weirdness](https://user-images.githubusercontent.com/43280/194126674-5511f30d-5fe3-4bc7-beb6-1bd6533d9afb.gif)

Tiny gaps persist in Firefox and Chrome:
<img width="201" alt="firefox-gap" src="https://user-images.githubusercontent.com/43280/194126796-bde3db0c-5fda-42c9-8752-4aa65c31f36c.png">
<img width="208" alt="chrome-gap" src="https://user-images.githubusercontent.com/43280/194126797-654e243f-9c3a-499d-bce7-e001e4683b72.png">

There’s a lot of misalignment in Safari:
<img width="720" alt="more-safari" src="https://user-images.githubusercontent.com/43280/194126940-71a96e6e-1023-4a9d-bd80-a97f9b5ab393.png">

Finally, this is maybe difficult with the existing button styles but I think there should be dividers between the buttons, they look strange to me without it:

<img width="888" alt="Boxel Components 2022-10-05 12-46-54" src="https://user-images.githubusercontent.com/43280/194127107-4da2ce8c-b5ee-432a-9f3b-d2f126407366.png">

Bootstrap, for example:
<img width="775" alt="Input group · Bootstrap v5 2 2022-10-05 12-47-50" src="https://user-images.githubusercontent.com/43280/194127187-2cc26105-0f01-484e-bfbf-60ffd32d6e97.png">

2022-10-05 20:53 UTC, lukemelia commented
I experimented with outline-offset to get tighter focus rects for this component but I observed inconsistent application of the rule between Safari and Chrome and could not get a good cross-browser effect when trying with negative values.

2022-10-05 23:40 UTC, lukemelia commented
It turns out to be quite difficult to do the vertical border for just buttons, so instead I added a CSS Var to control the interior border width.

2022-10-06 01:18 UTC, lukemelia commented
@backspace ready for another look

2022-10-06 14:32 UTC, backspace approved these changes
It all looks better! Safari has tiny gaps at some button edges but maybe we can defer that until this is actually in use:

<img width="909" alt="Boxel Components 2022-10-06 09-30-48" src="https://user-images.githubusercontent.com/43280/194340575-d946d59c-b519-40a2-ab88-9102678ada42.png">

2022-10-06 20:02 UTC, lukemelia commented
@backspace 
>Safari has tiny gaps at some button edges

Fixed, thanks!

2022-10-06 20:17 UTC, merged