cs-4687 update to get list of tasks from parameters
cardstack/cardstack pull request #3313
Opened 2022-10-12 10:01 UTC by tintinthong

2022-10-20 08:37 UTC, tintinthong commented on packages/cardpay-reward-scheduler/reward_scheduler/reward_program.py
> +                    return rules
p1

2022-10-20 08:38 UTC, tintinthong commented on packages/cardpay-reward-scheduler/reward_scheduler/reward_program.py
> +            self.run_rule(rule, explanation_block)
p2

2022-10-20 08:39 UTC, tintinthong commented on packages/cardpay-reward-programs/cardpay_reward_programs/main.py
> +    table = tree.as_arrow(explanation_id, explanation_data_arr)
p3

2022-10-20 08:39 UTC, tintinthong commented on packages/cardpay-reward-programs/cardpay_reward_programs/rule.py
> +        self.set_explanation_parameters(explanation_block)
p3

2022-10-20 08:49 UTC, tintinthong commented on packages/cardpay-reward-programs/cardpay_reward_programs/rules/flat_payment.py
> +        return explanation_data_arr
p5

2022-10-20 08:51 UTC, tintinthong commented on packages/cardpay-reward-programs/input/flat_payment/parameters.json
> +      }
p6

2022-10-21 15:17 UTC, IanCal requested changes

2022-10-25 08:12 UTC, IanCal approved these changes

2022-10-25 10:04 UTC, merged