Remove parquet map type to support s3 select
cardstack/cardstack pull request #3485
Opened 2022-12-08 13:20 UTC by tintinthong

2022-12-08 13:50 UTC, IanCal requested changes

2022-12-08 13:50 UTC, IanCal commented on packages/cardpay-reward-programs/cardpay_reward_programs/payment_tree.py
> +                    json.dumps(payment["explanationData"], separators=(",", ":"))
I think the cutom separators is just removing the spaces - if this is required for s3select can you add a comment and a test? That's the kind of subtle regression we could see at some point. If it works anyway it'd be good to use just json.dumps with its defaults.

2022-12-10 13:33 UTC, tintinthong commented
Additionally, I have added a quick fix to the indexer so it supports the old AND new column type. This should prevent anything from breaking

2022-12-15 08:23 UTC, tintinthong commented on packages/cardpay-reward-indexer/cardpay_reward_indexer/indexer.py
> +            last_submitted_root_block_number = 27715485
oh gosh

2022-12-19 13:31 UTC, IanCal approved these changes
lgtm :)

2022-12-19 13:31 UTC, merged