Shows only the latest attempts of canceled scheduled payment
cardstack/cardstack pull request #3666
Opened 2023-03-03 13:36 UTC by FadhlanR

Ticket: CS-5304

2023-03-06 09:58 UTC, jurgenwerk commented
For historic transparency maybe it be better to still display failed payments? And to only show the last one as canceled?

2023-03-06 15:01 UTC, FadhlanR commented
@jurgenwerk I have implemented your suggestion. My idea is to add a new field `isCanceled` field in the scheduled payment attempt object in the safe tools.

![Screenshot 2023-03-06 at 21 53 57](https://user-images.githubusercontent.com/12637010/223147747-f900d9a7-3d1e-4dd3-af80-2e14d34a7d6a.png)

2023-03-06 21:33 UTC, lukemelia requested changes
Naming needs improvement

2023-03-06 21:33 UTC, lukemelia commented on packages/safe-tools-client/app/services/scheduled-payments.ts
> +    const isAlreadyFoundTheLattestAttempt: Record<string, boolean> = {};
Maybe a better name would be `previouslySeenPayments`?

2023-03-07 09:34 UTC, jurgenwerk commented
Maybe all this can be reduced to:

```hbs
{{if (eq paymentAttempt.status 'failed')}}
  {{#if (and scheduledPaymentAttempt.scheduledPayment.isCanceled  (eq scheduledPaymentAttempt.id scheduledPaymentAttempt.scheduledPayment.lastScheduledPaymentAttemptId)}}
    Canceled
  {{else}}
    Failed
  {{/if}}
{{/if}}
```

2023-03-07 15:32 UTC, FadhlanR commented
@jurgenwerk I didn't realize we had that field, thanks for the suggestion. I've updated the code.

2023-03-08 09:00 UTC, merged